name: Testing de dependecias

on: [push]

jobs:
  uno:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Mensaje
        run: echo "Prueba de instalación de dependecias"
      
      - name: Touch file
        run: |
          touch hola.txt
          ls -al

      - name: Set text
        run: |
          echo "Dependecias" >> hola.txt
          ls -al

      - name: Read file
        run: |
          cat hola.txt

  dos:
    runs-on: ubuntu-latest
    needs: [uno]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Directorio
        run: ls -al
